
IF OBJECT_ID('DTI_SPJTPublicSISalesPlanSave') IS NOT NULL   
    DROP PROC DTI_SPJTPublicSISalesPlanSave  
GO  
  
-- v2014.04.07  
  
-- 공공SI사업경영계획_DTI-저장 by 이재천   
CREATE PROC DTI_SPJTPublicSISalesPlanSave  
    @xmlDocument    NVARCHAR(MAX),  
    @xmlFlags       INT = 0,  
    @ServiceSeq     INT = 0,   
    @WorkingTag     NVARCHAR(10)= '',  
    @CompanySeq     INT = 1,  
    @LanguageSeq    INT = 1,  
    @UserSeq        INT = 0,  
    @PgmSeq         INT = 0  
AS   
    CREATE TABLE #DTI_TPJTPublicSISalesPlan (WorkingTag NCHAR(1) NULL)    
    EXEC _SCAOpenXmlToTemp @xmlDocument, @xmlFlags, @CompanySeq, @ServiceSeq, 'DataBlock3', '#DTI_TPJTPublicSISalesPlan'   
    IF @@ERROR <> 0 RETURN    
    
    ALTER TABLE #DTI_TPJTPublicSISalesPlan ADD PlanYM NCHAR(6) NULL
    
    UPDATE #DTI_TPJTPublicSISalesPlan
       SET PlanYM = TITLE_IDX0_SEQ
      FROM #DTI_TPJTPublicSISalesPlan AS A 
    
    -- 로그 남기기    
    DECLARE @TableColumns NVARCHAR(4000)    
    
    -- Master 로그   
    SELECT @TableColumns = dbo._FGetColumnsForLog('DTI_TPJTPublicSISalesPlan')    
    
    -- DELETE      
    IF EXISTS ( SELECT TOP 1 1 FROM #DTI_TPJTPublicSISalesPlan WHERE WorkingTag = 'D' AND Status = 0 )    
    BEGIN 
        -- 삭제시 로그남기기
        INSERT INTO DTI_TPJTPublicSISalesPlanLog (LogUserSeq, LogDateTime, LogType, LogPgmSeq, 
                                                  CompanySeq, PlanYM, SMCostType, SMItemType, Value, 
                                                  LastUserSeq, LastDateTime, PgmSeq)
        
        SELECT @UserSeq, GETDATE(), 'D', @PgmSeq, 
               
               @CompanySeq, (SELECT PlanYear FROM #DTI_TPJTPublicSISalesPlan), 0,0,0,
               
               (SELECT TOP 1 LastUserSeq 
                  FROM DTI_TPJTPublicSISalesPlan AS A 
                  JOIN #DTI_TPJTPublicSISalesPlan AS B ON ( B.PlanYear = LEFT(A.PlanYM,4) ) 
                 WHERE CompanySeq = @CompanySeq 
               ), 
               (SELECT TOP 1 LastDateTime 
                  FROM DTI_TPJTPublicSISalesPlan AS A 
                  JOIN #DTI_TPJTPublicSISalesPlan AS B ON ( B.PlanYear = LEFT(A.PlanYM,4) ) 
                 WHERE CompanySeq = @CompanySeq 
               ), 
               (SELECT TOP 1 PgmSeq  
                  FROM DTI_TPJTPublicSISalesPlan AS A 
                  JOIN #DTI_TPJTPublicSISalesPlan AS B ON ( B.PlanYear = LEFT(A.PlanYM,4) ) 
                 WHERE CompanySeq = @CompanySeq 
               )
        
        DELETE B   
          FROM #DTI_TPJTPublicSISalesPlan AS A   
          JOIN DTI_TPJTPublicSISalesPlan  AS B ON ( B.CompanySeq = @CompanySeq AND LEFT(B.PlanYM,4) = A.PlanYear )   
         WHERE A.WorkingTag = 'D'   
           AND A.Status = 0   
    
        IF @@ERROR <> 0  RETURN  
    END    
    
    -- UPDATE      
    IF EXISTS ( SELECT TOP 1 1 FROM #DTI_TPJTPublicSISalesPlan WHERE WorkingTag = 'U' AND Status = 0 )    
    BEGIN  
        EXEC _SCOMLog @CompanySeq   ,        
                      @UserSeq      ,        
                      'DTI_TPJTPublicSISalesPlan'    , -- 테이블명        
                      '#DTI_TPJTPublicSISalesPlan'    , -- 임시 테이블명        
                      'PlanYM,SMCostType,SMItemType'   , -- CompanySeq를 제외한 키( 키가 여러개일 경우는 , 로 연결 )        
                      @TableColumns , '', @PgmSeq  -- 테이블 모든 필드명   
        UPDATE B   
           SET B.Value = A.Results, 
               B.LastUserSeq  = @UserSeq,  
               B.LastDateTime = GETDATE(),  
               B.PgmSeq       = @PgmSeq    
          FROM #DTI_TPJTPublicSISalesPlan AS A   
          JOIN DTI_TPJTPublicSISalesPlan  AS B ON ( B.CompanySeq = @CompanySeq AND B.PlanYM = A.TITLE_IDX0_SEQ AND B.SMCostType = A.SMCostType AND B.SMItemType = A.SMItemType ) 
         WHERE A.WorkingTag = 'U'   
           AND A.Status = 0      
        
        IF @@ERROR <> 0  RETURN  
    END    
    
    -- INSERT  
    IF EXISTS ( SELECT TOP 1 1 FROM #DTI_TPJTPublicSISalesPlan WHERE WorkingTag = 'A' AND Status = 0 )    
    BEGIN    
        INSERT INTO DTI_TPJTPublicSISalesPlan  
        (   
            CompanySeq, PlanYM, SMCostType, SMItemType, Value, 
            LastUserSeq, LastDateTime, PgmSeq   
        )   
        SELECT @CompanySeq, A.TITLE_IDX0_SEQ, A.SMCostType, A.SMItemType, A.Results, 
               @UserSeq, GETDATE(), @PgmSeq   
          FROM #DTI_TPJTPublicSISalesPlan AS A   
         WHERE A.WorkingTag = 'A'   
           AND A.Status = 0      
          
        IF @@ERROR <> 0 RETURN  
          
    END     
      
    SELECT * FROM #DTI_TPJTPublicSISalesPlan   
      
    RETURN  
GO
begin tran 
exec DTI_SPJTPublicSISalesPlanSave @xmlDocument=N'<ROOT>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>1</IDX_NO>
    <DataSeq>1</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>23124124.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201401</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>2</IDX_NO>
    <DataSeq>2</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201402</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>3</IDX_NO>
    <DataSeq>3</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201403</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>4</IDX_NO>
    <DataSeq>4</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201404</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>5</IDX_NO>
    <DataSeq>5</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201405</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>6</IDX_NO>
    <DataSeq>6</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201406</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>7</IDX_NO>
    <DataSeq>7</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201407</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>8</IDX_NO>
    <DataSeq>8</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201408</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>9</IDX_NO>
    <DataSeq>9</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201409</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>10</IDX_NO>
    <DataSeq>10</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201410</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>11</IDX_NO>
    <DataSeq>11</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201411</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>12</IDX_NO>
    <DataSeq>12</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201412</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>13</IDX_NO>
    <DataSeq>13</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>0</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419001</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>S/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201413</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>14</IDX_NO>
    <DataSeq>14</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201401</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>15</IDX_NO>
    <DataSeq>15</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>123124124.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201402</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>16</IDX_NO>
    <DataSeq>16</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201403</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>17</IDX_NO>
    <DataSeq>17</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201404</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>18</IDX_NO>
    <DataSeq>18</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201405</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>19</IDX_NO>
    <DataSeq>19</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201406</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>20</IDX_NO>
    <DataSeq>20</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201407</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>21</IDX_NO>
    <DataSeq>21</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201408</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>22</IDX_NO>
    <DataSeq>22</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201409</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>23</IDX_NO>
    <DataSeq>23</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201410</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>24</IDX_NO>
    <DataSeq>24</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201411</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>25</IDX_NO>
    <DataSeq>25</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201412</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>26</IDX_NO>
    <DataSeq>26</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>1</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419002</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>H/W</SMItemTypeName>
    <TITLE_IDX0_SEQ>201413</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>27</IDX_NO>
    <DataSeq>27</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201401</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>28</IDX_NO>
    <DataSeq>28</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201402</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>29</IDX_NO>
    <DataSeq>29</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201403</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>30</IDX_NO>
    <DataSeq>30</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>123124.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201404</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>31</IDX_NO>
    <DataSeq>31</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>12412.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201405</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>32</IDX_NO>
    <DataSeq>32</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201406</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>33</IDX_NO>
    <DataSeq>33</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201407</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>34</IDX_NO>
    <DataSeq>34</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201408</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>35</IDX_NO>
    <DataSeq>35</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201409</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>36</IDX_NO>
    <DataSeq>36</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201410</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>37</IDX_NO>
    <DataSeq>37</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201411</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>38</IDX_NO>
    <DataSeq>38</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201412</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>39</IDX_NO>
    <DataSeq>39</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>2</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419003</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>내부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201413</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>40</IDX_NO>
    <DataSeq>40</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201401</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>41</IDX_NO>
    <DataSeq>41</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201402</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>42</IDX_NO>
    <DataSeq>42</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>123124.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201403</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>43</IDX_NO>
    <DataSeq>43</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>23124.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201404</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>44</IDX_NO>
    <DataSeq>44</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>123124.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201405</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>45</IDX_NO>
    <DataSeq>45</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201406</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>46</IDX_NO>
    <DataSeq>46</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201407</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>47</IDX_NO>
    <DataSeq>47</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201408</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>48</IDX_NO>
    <DataSeq>48</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201409</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>49</IDX_NO>
    <DataSeq>49</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201410</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>50</IDX_NO>
    <DataSeq>50</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201411</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>51</IDX_NO>
    <DataSeq>51</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201412</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>52</IDX_NO>
    <DataSeq>52</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>3</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419004</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>외부용역</SMItemTypeName>
    <TITLE_IDX0_SEQ>201413</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>53</IDX_NO>
    <DataSeq>53</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201401</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>54</IDX_NO>
    <DataSeq>54</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201402</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>55</IDX_NO>
    <DataSeq>55</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201403</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>56</IDX_NO>
    <DataSeq>56</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>12312.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201404</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>57</IDX_NO>
    <DataSeq>57</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>124124.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201405</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>58</IDX_NO>
    <DataSeq>58</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201406</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>59</IDX_NO>
    <DataSeq>59</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201407</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>60</IDX_NO>
    <DataSeq>60</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201408</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>61</IDX_NO>
    <DataSeq>61</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201409</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>62</IDX_NO>
    <DataSeq>62</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201410</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>63</IDX_NO>
    <DataSeq>63</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201411</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>64</IDX_NO>
    <DataSeq>64</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201412</TITLE_IDX0_SEQ>
  </DataBlock3>
  <DataBlock3>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>65</IDX_NO>
    <DataSeq>65</DataSeq>
    <Selected>0</Selected>
    <Status>0</Status>
    <ROW_IDX>4</ROW_IDX>
    <SMCostType>1000418001</SMCostType>
    <SMCostTypeName>프로젝트매출[A1]</SMCostTypeName>
    <SMItemType>1000419011</SMItemType>
    <PlanYear>2014</PlanYear>
    <Results>0.00000</Results>
    <SMItemTypeName>매출조정금액</SMItemTypeName>
    <TITLE_IDX0_SEQ>201413</TITLE_IDX0_SEQ>
  </DataBlock3>
</ROOT>',@xmlFlags=2,@ServiceSeq=1022071,@WorkingTag=N'',@CompanySeq=1,@LanguageSeq=1,@UserSeq=50322,@PgmSeq=1018561
rollback 