
if object_id('KPXCM_TSEDesasterCHE') is null
begin 
CREATE TABLE KPXCM_TSEDesasterCHE 
(   
    CompanySeq int NOT NULL,  
    AccidentSeq int NOT NULL,  
    InjurySeq int NOT NULL,  
    EmpSeq int NOT NULL,   
    InjuryDate nchar(8) NOT NULL,   
    InjuryName nvarchar(100) NOT NULL,  
    HappenTime nchar(6) NOT NULL,  
    DisasterType int NOT NULL,   
    RelSftool int NOT NULL,    
    OperStatus int NOT NULL, 
    Weather int NULL   ,   
    HappenPlaceName nvarchar(100) NULL   ,   
    HappenOpnt int NULL   ,   
    HappenType int NULL   ,   
    SimWorkMan int NULL   ,   
    InjuryCauseName nvarchar(100) NULL   ,
    InjuryHrmName nvarchar(100) NULL   , 
    WorkContent int NULL   ,   
    RelsEqm nvarchar(50) NULL   ,  
    InjuryKind int NULL   ,   
    InjuryPart int NULL   ,   
    InjuryCnt int NULL   , 
    CloseDay int NULL   ,  
    CureDay int NULL   ,  
    NotSftyStatusName nvarchar(100) NULL   ,   
    NotSftyActName nvarchar(100) NULL   , 
    ManageCause int NULL   ,  
    ReportDate nchar(8) NULL   ,    
    ReprotUserSeq int NULL   ,  
    surveyFromDate nchar(8) NULL   ,  
    surveyToDate nchar(8) NULL   ,  
    surveyUserSeq int NULL   ,  
    AccidentOutline nvarchar(max) NULL   ,  
    AccidentCause nvarchar(max) NULL   ,  
    MngRemark nvarchar(max) NULL   ,   
    AccidentInjury nvarchar(max) NULL   ,   
    PreventMeasure nvarchar(max) NULL   , 
    FileSeq int NULL   ,   
    IndAcctSubDate nchar(8) NULL   ,  
    IndAcctApprDate nchar(8) NULL   ,   
    ClosePayReqDate nchar(8) NULL   ,   
    ClosePayReqAmt decimal(19,5) NULL   ,   
    DisCompBlDate nchar(8) NULL   ,   
    DisCompBlAmt decimal(19,5) NULL   ,  
    DisCompGrade int NULL   ,   
    HospitalDay int NULL   ,   
    RecuLossAmt decimal(19,5) NULL   ,    
    IndCloseReAmt decimal(19,5) NULL   ,  
    ComCloseReAmt decimal(19,5) NULL   ,   
    GSAmt decimal(19,5) NULL   ,  
    DisRewardAmt decimal(19,5) NULL   ,   
    ReplacementAmt decimal(19,5) NULL   ,   
    ProdLossAmt decimal(19,5) NULL   ,  
    LastDateTime datetime NOT NULL,   
    LastUserSeq int NOT NULL
) 
CREATE UNIQUE CLUSTERED INDEX IDXTempKPXCM_TSEDesasterCHE on KPXCM_TSEDesasterCHE(CompanySeq, AccidentSeq, InjurySeq)
end 


if object_id('KPXCM_TSEDesasterCHELog') is null
begin 
CREATE TABLE KPXCM_TSEDesasterCHELog 
(   
    LogSeq int identity NOT NULL,    
    LogUserSeq int NOT NULL,   
    LogDateTime datetime NOT NULL,   
    LogType nchar(1) NOT NULL,   
    LogPgmSeq int NULL   ,  
    CompanySeq int NOT NULL,   
    AccidentSeq int NOT NULL,    
    InjurySeq int NOT NULL,  
    EmpSeq int NOT NULL,   
    InjuryDate nchar(8) NOT NULL,    
    InjuryName nvarchar(100) NOT NULL, 
    HappenTime nchar(6) NOT NULL,   
    DisasterType int NOT NULL, 
    RelSftool int NOT NULL,    
    OperStatus int NOT NULL,  
    Weather int NULL   ,  
    HappenPlaceName nvarchar(100) NULL   , 
    HappenOpnt int NULL   ,   
    HappenType int NULL   ,  
    SimWorkMan int NULL   ,   
    InjuryCauseName nvarchar(100) NULL   ,  
    InjuryHrmName nvarchar(100) NULL   , 
    WorkContent int NULL   ,   
    RelsEqm nvarchar(50) NULL   ,   
    InjuryKind int NULL   ,  
    InjuryPart int NULL   ,   
    InjuryCnt int NULL   ,  
    CloseDay int NULL   ,    
    CureDay int NULL   ,   
    NotSftyStatusName nvarchar(100) NULL   ,   
    NotSftyActName nvarchar(100) NULL   ,  
    ManageCause int NULL   ,  
    ReportDate nchar(8) NULL   ,   
    ReprotUserSeq int NULL   ,   
    surveyFromDate nchar(8) NULL   , 
    surveyToDate nchar(8) NULL   ,
    surveyUserSeq int NULL   ,   
    AccidentOutline nvarchar(max) NULL   ,   
    AccidentCause nvarchar(max) NULL   ,   
    MngRemark nvarchar(max) NULL   ,  
    AccidentInjury nvarchar(max) NULL   , 
    PreventMeasure nvarchar(max) NULL   ,  
    FileSeq int NULL   ,   
    IndAcctSubDate nchar(8) NULL   ,  
    IndAcctApprDate nchar(8) NULL   ,  
    ClosePayReqDate nchar(8) NULL   , 
    ClosePayReqAmt decimal(19,5) NULL   ,   
    DisCompBlDate nchar(8) NULL   ,
    DisCompBlAmt decimal(19,5) NULL   ,   
    DisCompGrade int NULL   , 
    HospitalDay int NULL   ,  
    RecuLossAmt decimal(19,5) NULL   ,  
    IndCloseReAmt decimal(19,5) NULL   ,   
    ComCloseReAmt decimal(19,5) NULL   ,    
    GSAmt decimal(19,5) NULL   ,  
    DisRewardAmt decimal(19,5) NULL   ,    
    ReplacementAmt decimal(19,5) NULL   ,   
    ProdLossAmt decimal(19,5) NULL   ,  
    LastDateTime datetime NOT NULL, 
    LastUserSeq int NOT NULL
) 
CREATE UNIQUE CLUSTERED INDEX IDXTempKPXCM_TSEDesasterCHELog on KPXCM_TSEDesasterCHELog(LogSeq)
end 