  
IF OBJECT_ID('KPXCM_SPDSFCMonthProdPlanStockItemCheck') IS NOT NULL   
    DROP PROC KPXCM_SPDSFCMonthProdPlanStockItemCheck  
GO  
  
-- v2015.10.20  
  
-- 월생산계획-체크 by 이재천   
CREATE PROC KPXCM_SPDSFCMonthProdPlanStockItemCheck  
    @xmlDocument    NVARCHAR(MAX),  
    @xmlFlags       INT = 0,  
    @ServiceSeq     INT = 0,   
    @WorkingTag     NVARCHAR(10)= '',  
    @CompanySeq     INT = 1,  
    @LanguageSeq    INT = 1,  
    @UserSeq        INT = 0,  
    @PgmSeq         INT = 0  
AS   
    DECLARE @MessageType    INT,  
            @Status         INT,  
            @Results        NVARCHAR(250)   
      
    CREATE TABLE #KPXCM_TPDSFCMonthProdPlanStockItem( WorkingTag NCHAR(1) NULL )    
    EXEC _SCAOpenXmlToTemp @xmlDocument, @xmlFlags, @CompanySeq, @ServiceSeq, 'DataBlock2', '#KPXCM_TPDSFCMonthProdPlanStockItem'   
    IF @@ERROR <> 0 RETURN     
    

    DECLARE @MAXSerl INT 
    
    SELECT @MAXSerl = MAX(B.PlanSerl) 
      FROM #KPXCM_TPDSFCMonthProdPlanStockItem  AS A 
      JOIN KPXCM_TPDSFCMonthProdPlanStockItem   AS B ON ( B.CompanySeq = @CompanySeq AND B.PlanSeq = A.PlanSeq ) 
    

    
    UPDATE A 
       SET PlanSerl = ISNULL(@MAXSerl,0) + DataSeq 
      FROM #KPXCM_TPDSFCMonthProdPlanStockItem AS A 
     WHERE A.WorkingTag = 'A'
    
    SELECT * FROM #KPXCM_TPDSFCMonthProdPlanStockItem 
    
    RETURN  
go
begin tran 
exec KPXCM_SPDSFCMonthProdPlanStockItemCheck @xmlDocument=N'<ROOT>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>1</IDX_NO>
    <DataSeq>1</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>(){}[]!@#$%^&amp;*박소연!@#$%^&amp;*(){}[]</ItemName>
    <ItemNo>(){}[]!@#$%^&amp;*박소연!@#$%^&amp;*(){}[]</ItemNo>
    <ItemSeq>1052054</ItemSeq>
    <BaseQty>-645</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
    <TABLE_NAME>DataBlock2</TABLE_NAME>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>2</IDX_NO>
    <DataSeq>2</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>@ㅅㄷㄴㅅ</ItemName>
    <ItemNo>@ㅅㄷㄴㅅ</ItemNo>
    <ItemSeq>14497</ItemSeq>
    <BaseQty>470</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>3</IDX_NO>
    <DataSeq>3</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>@ㅅㄷㅋㅅ11</ItemName>
    <ItemNo>@ㅅㄷㅋㅅ11</ItemNo>
    <ItemSeq>14503</ItemSeq>
    <BaseQty>-1</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>4</IDX_NO>
    <DataSeq>4</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>@we</ItemName>
    <ItemNo>@we</ItemNo>
    <ItemSeq>14508</ItemSeq>
    <BaseQty>-1</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>5</IDX_NO>
    <DataSeq>5</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>@werewrwer</ItemName>
    <ItemNo>@wettteet</ItemNo>
    <ItemSeq>23051</ItemSeq>
    <BaseQty>8</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>6</IDX_NO>
    <DataSeq>6</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0106591</ItemName>
    <ItemNo>0106591</ItemNo>
    <ItemSeq>14526</ItemSeq>
    <BaseQty>-100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>7</IDX_NO>
    <DataSeq>7</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0407_범확제품</ItemName>
    <ItemNo>0407_범확제품_품번</ItemNo>
    <ItemSeq>1052002</ItemSeq>
    <BaseQty>200</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>8</IDX_NO>
    <DataSeq>8</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>17차 제품</ItemName>
    <ItemNo>17차 제품번호</ItemNo>
    <ItemSeq>23792</ItemSeq>
    <BaseQty>-1000</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>9</IDX_NO>
    <DataSeq>9</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>2000003</ItemName>
    <ItemNo>2000003</ItemNo>
    <ItemSeq>3</ItemSeq>
    <BaseQty>-10000</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>10</IDX_NO>
    <DataSeq>10</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>2014-노트북</ItemName>
    <ItemNo>2014-노트북</ItemNo>
    <ItemSeq>1001167</ItemSeq>
    <BaseQty>-96</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>11</IDX_NO>
    <DataSeq>11</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>27차 제품</ItemName>
    <ItemNo>27차 제품번호</ItemNo>
    <ItemSeq>23795</ItemSeq>
    <BaseQty>-100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>12</IDX_NO>
    <DataSeq>12</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>권오철_태광_LOT품목_11111111</ItemName>
    <ItemNo>OCKWON1</ItemNo>
    <ItemSeq>1001366</ItemSeq>
    <BaseQty>290</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>13</IDX_NO>
    <DataSeq>13</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>권오철_태광_LOT품목_2</ItemName>
    <ItemNo>OCKWON2</ItemNo>
    <ItemSeq>1001367</ItemSeq>
    <BaseQty>200</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>14</IDX_NO>
    <DataSeq>14</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>김경희_간단제품</ItemName>
    <ItemNo>김경희_간단제품</ItemNo>
    <ItemSeq>24854</ItemSeq>
    <BaseQty>-20</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>15</IDX_NO>
    <DataSeq>15</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>김민석_품목1</ItemName>
    <ItemNo>김민석_품목1</ItemNo>
    <ItemSeq>1052017</ItemSeq>
    <BaseQty>10</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>16</IDX_NO>
    <DataSeq>16</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>김상호제품001</ItemName>
    <ItemNo>김상호제품001</ItemNo>
    <ItemSeq>1052372</ItemSeq>
    <BaseQty>100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>17</IDX_NO>
    <DataSeq>17</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>김세호_test</ItemName>
    <ItemNo>3344</ItemNo>
    <ItemSeq>22568</ItemSeq>
    <BaseQty>-2</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>18</IDX_NO>
    <DataSeq>18</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>동윤초코렛</ItemName>
    <ItemNo>DYC001</ItemNo>
    <ItemSeq>1051288</ItemSeq>
    <BaseQty>-100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>19</IDX_NO>
    <DataSeq>19</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>박수영제품_TPC</ItemName>
    <ItemNo>박수영제품_TPC</ItemNo>
    <ItemSeq>1051791</ItemSeq>
    <BaseQty>120</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>20</IDX_NO>
    <DataSeq>20</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>보라-Lot품목</ItemName>
    <ItemNo>보라-Lot품목</ItemNo>
    <ItemSeq>26509</ItemSeq>
    <BaseQty>1000</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>21</IDX_NO>
    <DataSeq>21</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>세호-모니터</ItemName>
    <ItemNo>세호-모니터</ItemNo>
    <ItemSeq>23917</ItemSeq>
    <BaseQty>2</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>22</IDX_NO>
    <DataSeq>22</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>영업교육_박소연</ItemName>
    <ItemNo>영업교육_박소연</ItemNo>
    <ItemSeq>23520</ItemSeq>
    <BaseQty>195</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>23</IDX_NO>
    <DataSeq>23</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이범확_굳이테스트_제품</ItemName>
    <ItemNo>이범확_굳이테스트_제품_품번</ItemNo>
    <ItemSeq>1051994</ItemSeq>
    <BaseQty>10</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>24</IDX_NO>
    <DataSeq>24</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이범확_리얼테스트_제품</ItemName>
    <ItemNo>이범확_리얼테스트_제품_품번</ItemNo>
    <ItemSeq>1051990</ItemSeq>
    <BaseQty>100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>25</IDX_NO>
    <DataSeq>25</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이범확_테스트_제품1</ItemName>
    <ItemNo>이범확_테스트_제품1_품번</ItemNo>
    <ItemSeq>1051980</ItemSeq>
    <BaseQty>15</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>26</IDX_NO>
    <DataSeq>26</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이상정-제품1</ItemName>
    <ItemNo>이상정-제품1</ItemNo>
    <ItemSeq>15980</ItemSeq>
    <BaseQty>-11</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>27</IDX_NO>
    <DataSeq>27</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이용건-제품</ItemName>
    <ItemNo>yg-001</ItemNo>
    <ItemSeq>1051562</ItemSeq>
    <BaseQty>-29</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>28</IDX_NO>
    <DataSeq>28</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이준식_품목테스트</ItemName>
    <ItemNo>이준식_품목테스트</ItemNo>
    <ItemSeq>1052341</ItemSeq>
    <BaseQty>-10</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>29</IDX_NO>
    <DataSeq>29</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-생산-가습기</ItemName>
    <ItemNo>19920229200</ItemNo>
    <ItemSeq>1001315</ItemSeq>
    <BaseQty>829</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>30</IDX_NO>
    <DataSeq>30</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생산기본1</ItemName>
    <ItemNo>19920229201</ItemNo>
    <ItemSeq>1052127</ItemSeq>
    <BaseQty>100993863</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>31</IDX_NO>
    <DataSeq>31</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생산기본2</ItemName>
    <ItemNo>19920229201</ItemNo>
    <ItemSeq>1052129</ItemSeq>
    <BaseQty>997838</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>32</IDX_NO>
    <DataSeq>32</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생석회 제품1</ItemName>
    <ItemNo>장지연-송원-생석회 제품1</ItemNo>
    <ItemSeq>1052012</ItemSeq>
    <BaseQty>1995873</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>33</IDX_NO>
    <DataSeq>33</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생석회 제품2</ItemName>
    <ItemNo>장지연-송원-생석회 제품2</ItemNo>
    <ItemSeq>1052013</ItemSeq>
    <BaseQty>994860</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>34</IDX_NO>
    <DataSeq>34</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-Bag포장분1</ItemName>
    <ItemNo>장지연-송원-Bag포장분1</ItemNo>
    <ItemSeq>1052008</ItemSeq>
    <BaseQty>-17</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>35</IDX_NO>
    <DataSeq>35</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-Bag포장분2</ItemName>
    <ItemNo>장지연-송원-Bag포장분2</ItemNo>
    <ItemSeq>1052009</ItemSeq>
    <BaseQty>-18</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>36</IDX_NO>
    <DataSeq>36</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>전재일_제품_1</ItemName>
    <ItemNo>전재일_제품_1</ItemNo>
    <ItemSeq>1051583</ItemSeq>
    <BaseQty>-93</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>37</IDX_NO>
    <DataSeq>37</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>전재일_LOT관리</ItemName>
    <ItemNo>전재일_LOT관리</ItemNo>
    <ItemSeq>1052068</ItemSeq>
    <BaseQty>10</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>38</IDX_NO>
    <DataSeq>38</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>제동윤_과제제품</ItemName>
    <ItemNo>제동윤_과제제품</ItemNo>
    <ItemSeq>27533</ItemSeq>
    <BaseQty>-777</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>39</IDX_NO>
    <DataSeq>39</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>제품_김동한</ItemName>
    <ItemNo>제품_김동한</ItemNo>
    <ItemSeq>1000384</ItemSeq>
    <BaseQty>-5</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>40</IDX_NO>
    <DataSeq>40</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>제품_이지은</ItemName>
    <ItemNo>제품_이지은1234</ItemNo>
    <ItemSeq>27440</ItemSeq>
    <BaseQty>-55095</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>41</IDX_NO>
    <DataSeq>41</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>제품_jhlee</ItemName>
    <ItemNo>제품_jhlee</ItemNo>
    <ItemSeq>1052380</ItemSeq>
    <BaseQty>9</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>42</IDX_NO>
    <DataSeq>42</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>제품02_jhlee</ItemName>
    <ItemNo>제품02_jhlee</ItemNo>
    <ItemSeq>1052396</ItemSeq>
    <BaseQty>-11</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>43</IDX_NO>
    <DataSeq>43</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>제품idf_이지은</ItemName>
    <ItemNo>제품idf_이지은</ItemNo>
    <ItemSeq>1002274</ItemSeq>
    <BaseQty>11</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>44</IDX_NO>
    <DataSeq>44</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>짱맛있는 과자_MY</ItemName>
    <ItemNo>G_JJANG_01</ItemNo>
    <ItemSeq>1000446</ItemSeq>
    <BaseQty>300</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>45</IDX_NO>
    <DataSeq>45</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>DY제품</ItemName>
    <ItemNo>DYGE0001</ItemNo>
    <ItemSeq>26216</ItemSeq>
    <BaseQty>400</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>46</IDX_NO>
    <DataSeq>46</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>iPhone5</ItemName>
    <ItemNo>i5</ItemNo>
    <ItemSeq>15837</ItemSeq>
    <BaseQty>-60</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>47</IDX_NO>
    <DataSeq>47</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>Jykim2_제품(B)</ItemName>
    <ItemNo>0625JY002</ItemNo>
    <ItemSeq>25290</ItemSeq>
    <BaseQty>-300</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>48</IDX_NO>
    <DataSeq>48</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>PISTON</ItemName>
    <ItemNo>1234567890</ItemNo>
    <ItemSeq>1002329</ItemSeq>
    <BaseQty>720</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>49</IDX_NO>
    <DataSeq>49</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>SJ품목</ItemName>
    <ItemNo>SJ품목</ItemNo>
    <ItemSeq>1051713</ItemSeq>
    <BaseQty>1446</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>50</IDX_NO>
    <DataSeq>50</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>yh-제품A</ItemName>
    <ItemNo>yh-제품A</ItemNo>
    <ItemSeq>1052058</ItemSeq>
    <BaseQty>30</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>51</IDX_NO>
    <DataSeq>51</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>yjno2015081_제품</ItemName>
    <ItemNo>yjno2015081_제품</ItemNo>
    <ItemSeq>1052221</ItemSeq>
    <BaseQty>131</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>52</IDX_NO>
    <DataSeq>52</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>@asdfasdfasdf</ItemName>
    <ItemNo>@asdfasdfasdf</ItemNo>
    <ItemSeq>14527</ItemSeq>
    <BaseQty>900</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>53</IDX_NO>
    <DataSeq>53</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV 난연제어케이블</ItemName>
    <ItemNo>CRDC-06-005--00007</ItemNo>
    <ItemSeq>1000513</ItemSeq>
    <BaseQty>3300</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>54</IDX_NO>
    <DataSeq>54</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV 난연제어케이블</ItemName>
    <ItemNo>CRDC-06-011--00050</ItemNo>
    <ItemSeq>1000534</ItemSeq>
    <BaseQty>-4</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>55</IDX_NO>
    <DataSeq>55</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV 폴리에틸렌 난연케이블</ItemName>
    <ItemNo>CRDC-06-005--00008</ItemNo>
    <ItemSeq>1000514</ItemSeq>
    <BaseQty>100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>56</IDX_NO>
    <DataSeq>56</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV 폴리에틸렌 난연케이블</ItemName>
    <ItemNo>CRDC-06-011--00051</ItemNo>
    <ItemSeq>1000535</ItemSeq>
    <BaseQty>0</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>57</IDX_NO>
    <DataSeq>57</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV 폴리에틸렌 난연케이블</ItemName>
    <ItemNo>CRDC-06-011--00052</ItemNo>
    <ItemSeq>1000536</ItemSeq>
    <BaseQty>0</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>58</IDX_NO>
    <DataSeq>58</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV PVC절연 접지용전선</ItemName>
    <ItemNo>CRDC-06-005--00009</ItemNo>
    <ItemSeq>1000515</ItemSeq>
    <BaseQty>0</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>59</IDX_NO>
    <DataSeq>59</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV PVC절연 접지용전선</ItemName>
    <ItemNo>CRDC-06-011--00010</ItemNo>
    <ItemSeq>1000376</ItemSeq>
    <BaseQty>-5</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>60</IDX_NO>
    <DataSeq>60</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>0.6/1KV PVC절연 접지용전선</ItemName>
    <ItemNo>CRDC-06-011--00054</ItemNo>
    <ItemSeq>1000538</ItemSeq>
    <BaseQty>0</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>61</IDX_NO>
    <DataSeq>61</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>2014-디스크</ItemName>
    <ItemNo>2014-디스크</ItemNo>
    <ItemSeq>1001194</ItemSeq>
    <BaseQty>10000</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>62</IDX_NO>
    <DataSeq>62</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>곽상명_과제반제품</ItemName>
    <ItemNo>곽상명_과제반제품</ItemNo>
    <ItemSeq>27524</ItemSeq>
    <BaseQty>1</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>63</IDX_NO>
    <DataSeq>63</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>김상호반제품001</ItemName>
    <ItemNo>김상호반제품001</ItemNo>
    <ItemSeq>1052374</ItemSeq>
    <BaseQty>100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>64</IDX_NO>
    <DataSeq>64</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>김수창-반제품</ItemName>
    <ItemNo>김수창-반제품</ItemNo>
    <ItemSeq>1000919</ItemSeq>
    <BaseQty>10000</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>65</IDX_NO>
    <DataSeq>65</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>반제품_김동한</ItemName>
    <ItemNo>반제품_김동한</ItemNo>
    <ItemSeq>1000385</ItemSeq>
    <BaseQty>10</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>66</IDX_NO>
    <DataSeq>66</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>반제품_이지은</ItemName>
    <ItemNo>P123456789-SDFFESD2-jele</ItemNo>
    <ItemSeq>27441</ItemSeq>
    <BaseQty>-6</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>67</IDX_NO>
    <DataSeq>67</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>반제품_jhlee</ItemName>
    <ItemNo>반제품_jhlee</ItemNo>
    <ItemSeq>1052383</ItemSeq>
    <BaseQty>-10</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>68</IDX_NO>
    <DataSeq>68</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>세호-본체메모리</ItemName>
    <ItemNo>세호-본체메모리</ItemNo>
    <ItemSeq>23854</ItemSeq>
    <BaseQty>240440</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>69</IDX_NO>
    <DataSeq>69</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>영훈_반제품2</ItemName>
    <ItemNo>영훈_반제품2</ItemNo>
    <ItemSeq>1000806</ItemSeq>
    <BaseQty>100</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>70</IDX_NO>
    <DataSeq>70</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이범확_테스트_반제품1</ItemName>
    <ItemNo>이범확_테스트_반제품1_품번</ItemNo>
    <ItemSeq>1051985</ItemSeq>
    <BaseQty>-15</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>71</IDX_NO>
    <DataSeq>71</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이범확_테스트_반제품2</ItemName>
    <ItemNo>이범확_테스트_반제품2_품번</ItemNo>
    <ItemSeq>1051986</ItemSeq>
    <BaseQty>-15</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>72</IDX_NO>
    <DataSeq>72</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>이용건-반제품</ItemName>
    <ItemNo>yg-002</ItemNo>
    <ItemSeq>1051563</ItemSeq>
    <BaseQty>-11</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>73</IDX_NO>
    <DataSeq>73</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장경선_반제품g단위</ItemName>
    <ItemNo>장경선_반제품g단위_품번</ItemNo>
    <ItemSeq>1052191</ItemSeq>
    <BaseQty>4</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>74</IDX_NO>
    <DataSeq>74</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-생산-생수병결합부</ItemName>
    <ItemNo>19920229201</ItemNo>
    <ItemSeq>1001334</ItemSeq>
    <BaseQty>10000766</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>75</IDX_NO>
    <DataSeq>75</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생산기본반제</ItemName>
    <ItemNo>19920229201</ItemNo>
    <ItemSeq>1052128</ItemSeq>
    <BaseQty>999996</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>76</IDX_NO>
    <DataSeq>76</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생산기본반제1</ItemName>
    <ItemNo>19920229201</ItemNo>
    <ItemSeq>1052132</ItemSeq>
    <BaseQty>996984</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>77</IDX_NO>
    <DataSeq>77</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생석회 반제품1</ItemName>
    <ItemNo>장지연-송원-생석회 반제품1</ItemNo>
    <ItemSeq>1052015</ItemSeq>
    <BaseQty>999991</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>78</IDX_NO>
    <DataSeq>78</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>장지연-송원-생석회 반제품2</ItemName>
    <ItemNo>장지연-송원-생석회 반제품2</ItemNo>
    <ItemSeq>1052014</ItemSeq>
    <BaseQty>999895</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>79</IDX_NO>
    <DataSeq>79</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>천경민_반제품</ItemName>
    <ItemNo>천경민_반제품</ItemNo>
    <ItemSeq>1051526</ItemSeq>
    <BaseQty>-600</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>80</IDX_NO>
    <DataSeq>80</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>파상형 경질폴리에틸렌 전선관</ItemName>
    <ItemNo>CRDC-06-011--00072</ItemNo>
    <ItemSeq>1000556</ItemSeq>
    <BaseQty>200</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>81</IDX_NO>
    <DataSeq>81</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>hycheon_반제품</ItemName>
    <ItemNo>hycheon_반제품</ItemNo>
    <ItemSeq>27603</ItemSeq>
    <BaseQty>-15</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>82</IDX_NO>
    <DataSeq>82</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>mn_테스트반제품</ItemName>
    <ItemNo>mn_테스트반제품</ItemNo>
    <ItemSeq>1000574</ItemSeq>
    <BaseQty>-1</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>83</IDX_NO>
    <DataSeq>83</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>test_반제품2(이재천)</ItemName>
    <ItemNo>test_반제품2No(이재천)</ItemNo>
    <ItemSeq>1000591</ItemSeq>
    <BaseQty>-4</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>84</IDX_NO>
    <DataSeq>84</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>test_반제품3(이재천)</ItemName>
    <ItemNo>test_반제품3No(이재천)</ItemNo>
    <ItemSeq>1000617</ItemSeq>
    <BaseQty>-5</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>85</IDX_NO>
    <DataSeq>85</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>test_반제품5(이재천)</ItemName>
    <ItemNo>test_반제품5No(이재천)</ItemNo>
    <ItemSeq>1000619</ItemSeq>
    <BaseQty>-1</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>86</IDX_NO>
    <DataSeq>86</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>test_이재천(반제품)</ItemName>
    <ItemNo>P563009220-5K2C0TE1-0002</ItemNo>
    <ItemSeq>1000570</ItemSeq>
    <BaseQty>-2</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
  <DataBlock2>
    <WorkingTag>A</WorkingTag>
    <IDX_NO>87</IDX_NO>
    <DataSeq>87</DataSeq>
    <Status>0</Status>
    <Selected>0</Selected>
    <ItemName>test1_이재천(반제품)</ItemName>
    <ItemNo>test1_이재천(반제품)NO</ItemNo>
    <ItemSeq>1000626</ItemSeq>
    <BaseQty>-3</BaseQty>
    <ProdPlanQty>0</ProdPlanQty>
    <SalesPlanQty>0</SalesPlanQty>
    <SelfQty>0</SelfQty>
    <LastQty>0</LastQty>
    <PlanSeq>6</PlanSeq>
    <PlanSerl>0</PlanSerl>
  </DataBlock2>
</ROOT>',@xmlFlags=2,@ServiceSeq=1032672,@WorkingTag=N'',@CompanySeq=1,@LanguageSeq=1,@UserSeq=50322,@PgmSeq=1027069
rollback 