if OBJECT_ID('_TSLExpMaster') is null 
begin 
CREATE TABLE _TSLExpMaster 
(   
    CompanySeq int NOT NULL,    
    OrderSeq int NOT NULL,    
    AllowRange nvarchar(50) NULL   ,    
    Quantity nvarchar(50) NULL   ,    
    PaymentPrt nvarchar(1000) NULL   ,    
    VesselNomi nvarchar(50) NULL   ,    
    UMVesselName int NULL   ,    
    VesselName nvarchar(100) NULL   ,    
    ETANomiDate nvarchar(50) NULL   ,    
    RevisedETA nvarchar(50) NULL   ,    
    LocalAgentSeq int NULL   ,    
    ForwarderSeq int NULL   ,    
    DischargingAgent nvarchar(50) NULL   ,    
    ContainerNo nvarchar(50) NULL   ,    
    BookingNo nvarchar(50) NULL   ,    
    Freight nvarchar(50) NULL   ,    
    Customs nvarchar(50) NULL   ,    
    CYPickup nvarchar(50) NULL   ,    
    CarryLoc nvarchar(50) NULL   ,    
    ClosingDate nvarchar(50) NULL   ,    
    ContainerSize nvarchar(50) NULL   ,    
    ContainerQty nvarchar(50) NULL   ,    
    PKGS nvarchar(50) NULL   ,    
    BagNo nvarchar(50) NULL   ,    
    PackUnit nvarchar(50) NULL   ,    
    NetWeight nvarchar(50) NULL   ,    
    GrossWeight nvarchar(50) NULL   ,    
    Measurement nvarchar(50) NULL   ,    
    ShipWishDate nchar(8) NULL   ,    
    ShippedPlanDate nchar(8) NULL   ,    
    OutEmpName nvarchar(10) NULL   ,   
    OutEmpTelNo nvarchar(20) NULL   ,    
    TransCustSeq int NULL   ,    
    SRPrt nvarchar(1000) NULL   ,    
    RiskofMessrs nvarchar(1000) NULL   ,    
    DebitPrt nvarchar(1000) NULL   ,    
    LastUserSeq int NOT NULL,    
    LastDateTime datetime NOT NULL
) 
CREATE UNIQUE INDEX IDXTemp_TSLExpMaster on _TSLExpMaster(CompanySeq, OrderSeq)
end 

if OBJECT_ID('_TSLExpMasterLog') is null 
begin 
CREATE TABLE _TSLExpMasterLog 
(   
    LogSeq int identity NOT NULL,    
    LogUserSeq int NOT NULL,    
    LogDateTime datetime NOT NULL,    
    LogType nchar(1) NOT NULL,    
    CompanySeq int NOT NULL,    
    OrderSeq int NOT NULL,    
    AllowRange nvarchar(50) NULL   ,    
    Quantity nvarchar(50) NULL   ,    
    PaymentPrt nvarchar(1000) NULL   ,    
    VesselNomi nvarchar(50) NULL   ,    
    UMVesselName int NULL   ,    
    VesselName nvarchar(100) NULL   ,    
    ETANomiDate nvarchar(50) NULL   ,    
    RevisedETA nvarchar(50) NULL   ,    
    LocalAgentSeq int NULL   ,    
    ForwarderSeq int NULL   ,    
    DischargingAgent nvarchar(50) NULL   ,    
    ContainerNo nvarchar(50) NULL   ,    
    BookingNo nvarchar(50) NULL   ,    
    Freight nvarchar(50) NULL   ,    
    Customs nvarchar(50) NULL   ,    
    CYPickup nvarchar(50) NULL   ,    
    CarryLoc nvarchar(50) NULL   ,    
    ClosingDate nvarchar(50) NULL   ,    
    ContainerSize nvarchar(50) NULL   ,    
    ContainerQty nvarchar(50) NULL   ,    
    PKGS nvarchar(50) NULL   ,    
    BagNo nvarchar(50) NULL   ,    
    PackUnit nvarchar(50) NULL   ,    
    NetWeight nvarchar(50) NULL   ,    
    GrossWeight nvarchar(50) NULL   ,    
    Measurement nvarchar(50) NULL   ,    
    ShipWishDate nchar(8) NULL   ,    
    ShippedPlanDate nchar(8) NULL   ,    
    OutEmpName nvarchar(10) NULL   ,    
    OutEmpTelNo nvarchar(20) NULL   ,    
    TransCustSeq int NULL   ,    
    SRPrt nvarchar(1000) NULL   ,    
    RiskofMessrs nvarchar(1000) NULL   ,    
    DebitPrt nvarchar(1000) NULL   ,    
    LastUserSeq int NOT NULL,    
    LastDateTime datetime NOT NULL
) 
end 