if object_id('KPX_TEQChangeCmmReviewCHE') is null
begin 
CREATE TABLE KPX_TEQChangeCmmReviewCHE
(
    CompanySeq		INT 	 NOT NULL, 
    ReviewSeq		INT 	 NOT NULL, 
    ReviewDate		NCHAR(8) 	 NOT NULL, 
    DeptSeq		INT 	 NULL, 
    UMResult		INT 	 NULL, 
    Contents1		NVARCHAR(1000) 	 NULL, 
    DeptName1		NVARCHAR(1000) 	 NULL, 
    Date1		NVARCHAR(1000) 	 NULL, 
    Contents2		NVARCHAR(1000) 	 NULL, 
    DeptName2		NVARCHAR(1000) 	 NULL, 
    Date2		NVARCHAR(1000) 	 NULL, 
    Contents3		NVARCHAR(1000) 	 NULL, 
    DeptName3		NVARCHAR(1000) 	 NULL, 
    Date3		NVARCHAR(1000) 	 NULL, 
    Contents4		NVARCHAR(1000) 	 NULL, 
    DeptName4		NVARCHAR(1000) 	 NULL, 
    Date4		NVARCHAR(1000) 	 NULL, 
    Contents6		NVARCHAR(1000) 	 NULL, 
    DeptName6		NVARCHAR(1000) 	 NULL, 
    Date6		NVARCHAR(1000) 	 NULL, 
    Contents7		NVARCHAR(1000) 	 NULL, 
    DeptName7		NVARCHAR(1000) 	 NULL, 
    Date7		NVARCHAR(1000) 	 NULL, 
    Contents8		NVARCHAR(1000) 	 NULL, 
    DeptName8		NVARCHAR(1000) 	 NULL, 
    Date8		NVARCHAR(1000) 	 NULL, 
    IsProcDept		NCHAR(1) 	 NULL, 
    IsProdDept		NCHAR(1) 	 NULL, 
    IsStdDept		NCHAR(1) 	 NULL, 
    IsSafeDept		NCHAR(1) 	 NULL, 
    DeptEtc		NVARCHAR(100) 	 NULL, 
    IsAct		NCHAR(1) 	 NULL, 
    IsAdd		NCHAR(1) 	 NULL, 
    IsNot		NCHAR(1) 	 NULL, 
    TotEtc		NVARCHAR(100) 	 NULL, 
    ChangeRequestSeq		INT 	 NULL, 
    LastUserSeq		INT 	 NULL, 
    LastDateTime		DATETIME 	 NULL

)
create unique clustered index idx_KPX_TEQChangeCmmReviewCHE on KPX_TEQChangeCmmReviewCHE(CompanySeq,ReviewSeq) 
end 

if object_id('KPX_TEQChangeCmmReviewCHELog') is null
begin 
CREATE TABLE KPX_TEQChangeCmmReviewCHELog
(
    LogSeq		INT IDENTITY(1,1) NOT NULL, 
    LogUserSeq		INT NOT NULL, 
    LogDateTime		DATETIME NOT NULL, 
    LogType		NCHAR(1) NOT NULL, 
    LogPgmSeq		INT NULL, 
    CompanySeq		INT 	 NOT NULL, 
    ReviewSeq		INT 	 NOT NULL, 
    ReviewDate		NCHAR(8) 	 NOT NULL, 
    DeptSeq		INT 	 NULL, 
    UMResult		INT 	 NULL, 
    Contents1		NVARCHAR(1000) 	 NULL, 
    DeptName1		NVARCHAR(1000) 	 NULL, 
    Date1		NVARCHAR(1000) 	 NULL, 
    Contents2		NVARCHAR(1000) 	 NULL, 
    DeptName2		NVARCHAR(1000) 	 NULL, 
    Date2		NVARCHAR(1000) 	 NULL, 
    Contents3		NVARCHAR(1000) 	 NULL, 
    DeptName3		NVARCHAR(1000) 	 NULL, 
    Date3		NVARCHAR(1000) 	 NULL, 
    Contents4		NVARCHAR(1000) 	 NULL, 
    DeptName4		NVARCHAR(1000) 	 NULL, 
    Date4		NVARCHAR(1000) 	 NULL, 
    Contents6		NVARCHAR(1000) 	 NULL, 
    DeptName6		NVARCHAR(1000) 	 NULL, 
    Date6		NVARCHAR(1000) 	 NULL, 
    Contents7		NVARCHAR(1000) 	 NULL, 
    DeptName7		NVARCHAR(1000) 	 NULL, 
    Date7		NVARCHAR(1000) 	 NULL, 
    Contents8		NVARCHAR(1000) 	 NULL, 
    DeptName8		NVARCHAR(1000) 	 NULL, 
    Date8		NVARCHAR(1000) 	 NULL, 
    IsProcDept		NCHAR(1) 	 NULL, 
    IsProdDept		NCHAR(1) 	 NULL, 
    IsStdDept		NCHAR(1) 	 NULL, 
    IsSafeDept		NCHAR(1) 	 NULL, 
    DeptEtc		NVARCHAR(100) 	 NULL, 
    IsAct		NCHAR(1) 	 NULL, 
    IsAdd		NCHAR(1) 	 NULL, 
    IsNot		NCHAR(1) 	 NULL, 
    TotEtc		NVARCHAR(100) 	 NULL, 
    ChangeRequestSeq		INT 	 NULL, 
    LastUserSeq		INT 	 NULL, 
    LastDateTime		DATETIME 	 NULL
)
end 